/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.TourDaDatBLL;
import DTO.TourDaDat;
import com.toedter.calendar.JDateChooser;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class FormQuanLiDatTour extends javax.swing.JFrame {
    ArrayList<TourDaDat> listtour = new ArrayList<>();
    TourDaDat tour = new TourDaDat();
    int vitri;

    public FormQuanLiDatTour(JButton btnSua, JButton btnTim, JButton btnXoa, JLabel jLabel1, JLabel jLabel2, JLabel jLabel4, JLabel jLabel5, JScrollPane jScrollPane1, JLabel lblID, JLabel lblID1, JLabel lblName, JLabel lblPhone, JTable tbquantidattour, JTextField txtGmail, JSpinner txtNguoiLon, JTextField txtTenKhach, JSpinner txtTreEm, JTextField txtmatourdat, JDateChooser txtngaykhoihanh, JTextField txtsdt) throws HeadlessException {
        this.btnSua = btnSua;
        this.btnTim = btnTim;
        this.btnXoa = btnXoa;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel4 = jLabel4;
        this.jLabel5 = jLabel5;
        this.jScrollPane1 = jScrollPane1;
        this.lblID = lblID;
        this.lblID1 = lblID1;
        this.lblName = lblName;
        this.lblPhone = lblPhone;
        this.tbquantidattour = tbquantidattour;
        this.txtGmail = txtGmail;
        this.txtNguoiLon = txtNguoiLon;
        this.txtTenKhach = txtTenKhach;
        this.txtTreEm = txtTreEm;
        this.txtmatourdat = txtmatourdat;
        this.txtngaykhoihanh = txtngaykhoihanh;
        this.txtsdt = txtsdt;
    }
    /**
     * Creates new form FormQuanLiDatTour
     */
    public FormQuanLiDatTour() {
        initComponents();
        setLocationRelativeTo(this);
        hienthidanhsach();
    }
    
    public void clearform(){
        
    }
    public void xoatour(){
        if(TourDaDatBLL.getInstance().XoatourDaDat(tour)){
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
        }
    }
    public void capnhat(){
        String string = null;
        try {
            java.util.Date date = txtngaykhoihanh.getDate();
            string  = new SimpleDateFormat("yyyy-MM-dd").format(date);
        } catch (NullPointerException e) {
        }
        tour = new TourDaDat(listtour.get(vitri).getMadanhsach(), listtour.get(vitri).getTentour(),txtTenKhach.getText(),
                            string,listtour.get(vitri).getNgaydattour(), txtsdt.getText(),
                            txtGmail.getText() ,Integer.parseInt(txtNguoiLon.getValue().toString()),Integer.parseInt(txtTreEm.getValue().toString()),
                            listtour.get(vitri).getTongtien());
        tour.setMakhachhang(listtour.get(vitri).getMakhachhang());
        TourDaDatBLL.getInstance().CapNhatTourDaDat(tour);
    }
    public void hienthidanhsach(){
        DefaultTableModel model = (DefaultTableModel) tbquantidattour.getModel();
        model.setRowCount(0);
        TourDaDatBLL.getInstance().getTourDaDaDat(listtour);
        for (TourDaDat tourDaDat : listtour) {
            Object mang[] = {tourDaDat.getMadanhsach(),tourDaDat.getTentour(),tourDaDat.getNgaykhoihanh(),tourDaDat.getNgaydattour()
                                ,tourDaDat.getTenkhachhang(),tourDaDat.getSodienthoai(),tourDaDat.getGmail(),tourDaDat.getSonguoilon()
                                ,tourDaDat.getSotreem(),tourDaDat.getTongtien()};
            model.addRow(mang);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbquantidattour = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lblPhone = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        txtTenKhach = new javax.swing.JTextField();
        txtmatourdat = new javax.swing.JTextField();
        lblID1 = new javax.swing.JLabel();
        txtngaykhoihanh = new com.toedter.calendar.JDateChooser();
        txtNguoiLon = new javax.swing.JSpinner();
        txtTreEm = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Quản lí đặt tour đã đặt");

        lblName.setText("Tên Khách");

        lblID.setText("Ngày khởi hành");

        tbquantidattour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tour đã đjăt", "Tên tour", "Ngày khởi hành", "Ngày đặt tour", "Tên khách đặt", "Số điện thoại", "Gmail", "Người lớn", "Trẻ em", "Tổng tiền"
            }
        ));
        tbquantidattour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbquantidattourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbquantidattour);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lblPhone.setText("Di Động");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel2.setText("Gmail");

        lblID1.setText("Mã tour đã đặt");

        jLabel4.setText("Số Người Lớn :");
        jLabel4.setToolTipText("");

        jLabel5.setText("Số Trẻ Em :");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 237, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmatourdat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPhone)
                                    .addComponent(lblID)
                                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtngaykhoihanh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNguoiLon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTreEm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID1)
                    .addComponent(txtmatourdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtngaykhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblID))
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone)
                            .addComponent(jLabel2)
                            .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNguoiLon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTreEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbquantidattourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbquantidattourMouseClicked
        vitri = tbquantidattour.getSelectedRow();
        
        
        txtTenKhach.setText((String) tbquantidattour.getModel().getValueAt(vitri, 4));
        txtsdt.setText((String) tbquantidattour.getModel().getValueAt(vitri, 5));
        txtGmail.setText((String) tbquantidattour.getModel().getValueAt(vitri, 6));
        txtNguoiLon.setValue(tbquantidattour.getModel().getValueAt(vitri, 7));
        txtTreEm.setValue(tbquantidattour.getModel().getValueAt(vitri, 8));
        txtngaykhoihanh.setDateFormatString("yyyy-MM-dd");
         try {
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tbquantidattour.getModel().getValueAt(vitri, 2).toString());
            
            txtngaykhoihanh.setDate(date);

        } catch (ParseException ex) {
            Logger.getLogger(FormGiaoDienTour.class.getName()).log(Level.SEVERE, null, ex);
        }
        tour.setMadanhsach(listtour.get(vitri).getMadanhsach());
        tour.setMakhachhang(listtour.get(vitri).getMakhachhang());
    }//GEN-LAST:event_tbquantidattourMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
                // TODO add your handling code here:
        capnhat();
        hienthidanhsach();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        xoatour();
        hienthidanhsach();
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiDatTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiDatTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiDatTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiDatTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLiDatTour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTable tbquantidattour;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JSpinner txtNguoiLon;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JSpinner txtTreEm;
    private javax.swing.JTextField txtmatourdat;
    private com.toedter.calendar.JDateChooser txtngaykhoihanh;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
