/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.TourBLL;
import Callback.CallbackTour;
import DTO.LichTrinh;
import DTO.Tour;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class FormChiTietTour extends javax.swing.JFrame {
    CallbackTour callbackTour;
    Tour tour;
    /**
     * Creates new form FormChiTietTour
     */
    public FormChiTietTour() {
        initComponents();
        setLocationRelativeTo(this);
        hienthilistanh();
    }
    
    
    
    
    
    public void getThongTinTour(String matour){
        tour = TourBLL.getInstance().getTourTheoMa(matour);
        txtMatour.setText(tour.getMatour());
        txtTenTour.setText(tour.getTentour());
        txtDiemXuatPhat.setText(tour.getDiemxuatphat());
        txtThoiGianTour.setText(tour.getThoigiantour());
        txtDiemDuLich.setText(tour.getDiemdulich());
        txtDichVu.setText(tour.getDichvu());
        hienthilichtrinh();
        
    
    }
    
    public void hienthilichtrinh(){
        txtngay1.setText(tour.getLichtrinh().get(0).getNoidung()+"");
        txtngay2.setText(tour.getLichtrinh().get(1).getNoidung()+"");
        txtngay3.setText(tour.getLichtrinh().get(2).getNoidung()+"");
        
    }
    public void hienthilistanh(){
            listanh.removeAll();
            listanh.revalidate();
            listanh.setLayout(new FlowLayout());
        
        for (int i = 0; i < 10; i++) {
            
            final JPanel p = new JPanel();
            p.setBorder(BorderFactory.createLineBorder(Color.yellow));
            p.setLayout(new BoxLayout(p, BoxLayout.Y_AXIS));
            
            JLabel labelImage = new JLabel();
            labelImage.setHorizontalAlignment(JLabel.CENTER);
            p.add(labelImage);
            try {
                BufferedImage image = ImageIO.read(new File("dulich.jpg"));
                ImageIcon icon = new ImageIcon(image.getScaledInstance(250, 150, image.SCALE_SMOOTH));
                labelImage.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
            }
            p.add(labelImage);
            listanh.add(p);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        txtTenTour = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMatour = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtThoiGianTour = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNgayKhoiHanh = new javax.swing.JLabel();
        txtDiemXuatPhat = new javax.swing.JLabel();
        txtDiemDuLich = new javax.swing.JLabel();
        tablelichtrinh = new javax.swing.JTabbedPane();
        table1 = new javax.swing.JScrollPane();
        txtngay1 = new javax.swing.JTextArea();
        table2 = new javax.swing.JScrollPane();
        txtngay2 = new javax.swing.JTextArea();
        table3 = new javax.swing.JScrollPane();
        txtngay3 = new javax.swing.JTextArea();
        table4 = new javax.swing.JScrollPane();
        txtngay4 = new javax.swing.JTextArea();
        table5 = new javax.swing.JScrollPane();
        txtngay5 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listanh = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtDichVu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTenTour.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtTenTour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTenTour.setText("Hà nội - Hạ Long - Bãi Cháy - Cô tô");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Mã tour :");

        txtMatour.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtMatour.setText("HNQN01");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Ngày khởi hành :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Xuất phát: ");

        txtThoiGianTour.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtThoiGianTour.setText("4 ngày");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Thời gian :");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Điểm du lịch :");

        txtNgayKhoiHanh.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtNgayKhoiHanh.setText("28/5/2020");

        txtDiemXuatPhat.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtDiemXuatPhat.setText("Hà nội");

        txtDiemDuLich.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtDiemDuLich.setText("Vịnh Hạ Long - Bãi Cháy - Đảo Cô Tô");

        txtngay1.setColumns(20);
        txtngay1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtngay1.setRows(5);
        txtngay1.setText("NGÀY 1: ĐÓN KHÁCH - THAM QUAN HÀ NỘI (ĂN TRƯA)\n\n4h30: Quý khách có mặt tại sân bay làm thủ tục đáp chuyến bay đến Nội Bài (vé máy bay cung cấp khi Quý khách đặt tour). Xe đón Quý khách tại Nội Bài đưa về tham quan Hà Nội, đầu tiên quý khách tham quan Chùa Trấn Quốc.\n\n09h30:  Tham quan quần thể di tích chủ tịch Hồ Chí Minh, Bảo Tàng Hồ Chí Minh và Nhà sàn, Ao cá Bác Hồ.\n\n10h30:  Điểm tham quan tiếp theo là Chùa Một Cột.\n\n11h00:  Tham quan Văn Miếu Quốc Tử Giám - trường đại học đầu tiên của Việt Nam, cũng là nơi thờ Khổng Tử, Chu Văn An.\n\n12h30:  Dừng chân nghỉ ngơi, ăn trưa tại nhà hàng trong khu vực Phố cổ.\n\n13h40: Tiếp tục chương trình khám phá cuộc sống hàng ngày của gốm truyền thống tại làng gốm Bát Tràng trên bờ sông Hồng. Bạn biết về lịch sử hơn 700 năm của làng, tham quan các phòng trưng bày các sản phẩm gốm Bát Tràng.\n\n15h30:  Tham quan chụp hình tại  khu vực Hồ Hoàn Kiếm - Đền Ngọc Sơn.\n\n15h40 - 16h00: Trở lại khách sạn, chia tay Quý khách kết thúc chương trình.\n\nSau đó, xe đưa Quý khách về nhận phòng khách sạn, tự do ăn tối và dạo chơi Phố cổ Hà nội về đêm.");
        table1.setViewportView(txtngay1);

        tablelichtrinh.addTab("Ngày 1", table1);

        txtngay2.setColumns(20);
        txtngay2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtngay2.setRows(5);
        txtngay2.setText("NGÀY 2: HÀ NỘI – HẠ LONG  (ĂN SÁNG, TRƯA,TỐI)\n\n8h: Xe và hướng dẫn viên đón Quý khách khởi hành đi Hạ Long (Quảng Ninh). \n\n12h30:  Đến cảng tàu quốc tế tuần châu, Hướng dẫn viên sẽ mua vé để quý khách lên tàu ra tham quan Vịnh Hạ Long.\n\n13h00: Sau khi lên tàu, Quý khách thưởng thức đồ uống chào mừng và dùng bữa trưa trên tàu.\n\n13h45: Sau khi thưởng thức bữa trưa, du khách có thể đứng trên boong tàu để chụp ảnh, ngắm nhìn vịnh hạ long. Điểm đầu tiên du khách được thăm quan chính là hòn Chó Đá đứng sừng sững quay lưng ra biển. \n\n14h00: Sau khi tham quan hòn chó đá là đến Hòn Đỉnh Hương trước khi tàu đưa du khách thăm quan khu làng chài – ba hang. Đến với khu làng chài – ba hang tàu sẽ chờ đợi du khách 1 tiếng cho các hoạt động ngồi thuyền tre để người dân địa phương đưa đi tham quan hoặc  tự do chèo xuồng kayat.\n\n15h00: Tiếp tục lên tàu để tham quan tham quan hòn Trống Mái (hòn gà chọi).\n\n15h30: Du khách vào tham quan Động thiên cung.\n\nSau đó, xe đưa quý khách trở lại bến tàu, Quý khách lên xe về Hà Nội, ăn tối và nghỉ đêm tại Hà Nội.\n\n");
        table2.setViewportView(txtngay2);

        tablelichtrinh.addTab("Ngày 2", table2);

        txtngay3.setColumns(20);
        txtngay3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtngay3.setRows(5);
        txtngay3.setText("NGÀY 3: HÀ NỘI – LÀO CAI- SAPA (ĂN SÁNG, TRƯA, TỐI)\n\n6h30: Quý khách trả phòng khách sạn, xe đón, đưa Quý khách đi du lịch SaPa – Thành phố trong sương.\n\n13h00: Tới Sapa, Quý khách ăn trưa, nghỉ ngơi. Nhận phòng khách sạn và thưởng thức không khí trong lành và phong cảnh hữu tình của Sapa. \n\nChiều: Quý khách khởi động bằng một cuộc leo lên đỉnh Hàm Rồng gồm có: Vườn Lan 1-2, vườn Lê, vườn Táo Mèo, Vườn hoa Trung Tâm, Hòn Đá Gãy, Cổng Trời, Đầu Rồng, Hòn Cá Sấu, Khu Thiên Thách Lâm, Hòn Phật Bà, Sân Mây, tháp truyền hình …\n\nTối: Ăn tối và nghỉ đêm tại Sa Pa. Đặc biệt vào tối thứ bảy Quý khách có thể tham dự phiên Chợ Tình của người Dao Đỏ ");
        table3.setViewportView(txtngay3);

        tablelichtrinh.addTab("Ngày 3", table3);

        txtngay4.setColumns(20);
        txtngay4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtngay4.setRows(5);
        table4.setViewportView(txtngay4);

        tablelichtrinh.addTab("Ngày 4", table4);

        txtngay5.setColumns(20);
        txtngay5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtngay5.setRows(5);
        table5.setViewportView(txtngay5);

        tablelichtrinh.addTab("Ngày 5", table5);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Lịch Trình:");

        javax.swing.GroupLayout listanhLayout = new javax.swing.GroupLayout(listanh);
        listanh.setLayout(listanhLayout);
        listanhLayout.setHorizontalGroup(
            listanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        listanhLayout.setVerticalGroup(
            listanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(listanh);

        jButton1.setBackground(new java.awt.Color(150, 238, 238));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Đặt tour");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Dịch vụ: ");

        txtDichVu.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtDichVu.setText("Khách san 4*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTenTour)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatour)
                            .addComponent(txtDiemXuatPhat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayKhoiHanh)
                            .addComponent(txtDiemDuLich))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDichVu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThoiGianTour))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tablelichtrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtTenTour))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatour)
                    .addComponent(jLabel4)
                    .addComponent(txtThoiGianTour)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayKhoiHanh))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiemXuatPhat)
                    .addComponent(jLabel8)
                    .addComponent(txtDiemDuLich))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDichVu)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(357, 357, 357))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tablelichtrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        FormDangKyTour dangKyTour = new FormDangKyTour();
        dangKyTour.hienthithongtin(tour);
        dangKyTour.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FormGiaoDienTour formGiaoDienTour = new FormGiaoDienTour();
        formGiaoDienTour.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChiTietTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChiTietTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChiTietTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChiTietTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChiTietTour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel listanh;
    private javax.swing.JScrollPane table1;
    private javax.swing.JScrollPane table2;
    private javax.swing.JScrollPane table3;
    private javax.swing.JScrollPane table4;
    private javax.swing.JScrollPane table5;
    private javax.swing.JTabbedPane tablelichtrinh;
    private javax.swing.JLabel txtDichVu;
    private javax.swing.JLabel txtDiemDuLich;
    private javax.swing.JLabel txtDiemXuatPhat;
    private javax.swing.JLabel txtMatour;
    private javax.swing.JLabel txtNgayKhoiHanh;
    private javax.swing.JLabel txtTenTour;
    private javax.swing.JLabel txtThoiGianTour;
    private javax.swing.JTextArea txtngay1;
    private javax.swing.JTextArea txtngay2;
    private javax.swing.JTextArea txtngay3;
    private javax.swing.JTextArea txtngay4;
    private javax.swing.JTextArea txtngay5;
    // End of variables declaration//GEN-END:variables
}
